# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('news', models.BooleanField(default=True)),
                ('select', models.CharField(choices=[('friends', 'Friends'), ('search', 'Search Engine'), ('add', 'Advertisement'), ('others', 'Other')], max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
