# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_newsletter_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='select',
            field=models.CharField(choices=[('friends', 'Search Engine'), ('add', 'Advertisement'), ('others', 'Other')], default='friends', max_length=100),
        ),
    ]
