# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20180413_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='find',
            field=models.CharField(choices=[('friends', 'Friends'), ('search', 'Search Engine'), ('ad', 'Advertisement'), ('other', 'Other')], default='friends', max_length=100, null=True),
        ),
    ]
