# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='pin',
            field=models.BigIntegerField(),
        ),
    ]
