# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180413_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
