# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20180413_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='city',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Bengaluru', 'Bengaluru')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
