# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-18 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20180416_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='order',
            field=models.CharField(choices=[('1', 'Smoked Chipotle Rice'), ('2', 'Baked Beans with Vegetables'), ('3', 'Simple italian pizza with cherry tomatoes'), ('4', 'Autumn pumpkin soup'), ('5', 'Caesar Salad'), ('6', 'Granola with cherries and strawberries'), ('7', 'Black Bean Tacos With Olives'), ('8', 'Hummus and Pita bread'), ('9', 'Lentil and Charred Broccoli Chaat'), ('10', 'Blue Corn Breakfast Tacos With Scrambled Eggs')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
