# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-19 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20180419_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='order',
            field=models.CharField(choices=[('Smoked Chipotle Rice', 'Smoked Chipotle Rice'), ('Baked Beans with Vegetables', 'Baked Beans with Vegetables'), ('Simple italian pizza with cherry tomatoes', 'Simple italian pizza with cherry tomatoes'), ('Autumn pumpkin soup', 'Autumn pumpkin soup'), ('Caesar Salad', 'Caesar Salad'), ('Granola with cherries and strawberries', 'Granola with cherries and strawberries'), ('Black Bean Tacos With Olives', 'Black Bean Tacos With Olives'), ('Hummus and Pita bread', 'Hummus and Pita bread'), ('Lentil and Charred Broccoli Chaat', 'Lentil and Charred Broccoli Chaat'), ('Blue Corn Breakfast Tacos With Scrambled Eggs', 'Blue Corn Breakfast Tacos With Scrambled Eggs')], max_length=100, null=True),
        ),
    ]
